jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: jx-variables
      uses: docker://ghcr.io/jenkins-x/jx-boot:3.3.4
      with:
        entrypoint: .github/workflows/jenkins-x/gitops-variables.sh
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: build-make-linux
      uses: docker://golang:1.17.11
      with:
        args: -c "make linux"
        entrypoint: /bin/sh
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: build-make-test
      uses: docker://golang:1.17.11
      with:
        args: -c "make test"
        entrypoint: /bin/sh
on:
  pull_request:
    branches:
    - main
    - master
